micronaut:
  application:
    name: corsTest
  server:
    port: -1
    cors:
      enabled: true
      single-header: true
      configurations:
        web:
          maxAge: 3600
          allowedOrigins:
            - ^http(|s):\/\/(|www\.)(.*?)(|:[0-9]+)$
          exposedHeaders:
            - Content-Type
            - Authorization
            - X-Api-Version
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
  router:
    versioning:
      enabled: true
      default-version: 1
      parameter:
        enabled: false
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-Api-Version'
          - 'Accept-Version'
